[package]
name = "moonbags_aida"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }
aida = { local = "sources_deps/aida" }
CetusClmm = { local = "./externals/cetus_clmm" }
LpBurn = { local = "./externals/lp_burn" }
TurbosCLMM = { local = "./externals/turbos_clmm" }

[addresses]
moonbags_aida = "0x0"
aida = "0xcee208b8ae33196244b389e61ffd1202e7a1ae06c8ec210d33402ff649038892"
